### PR TITLE
Improved inter-site registration for the NIST data 

### PR DESCRIPTION
**Pull request by jcohenadad**
Related to #1

To test:
~~~
# checkout this branch, then update dependencies:
pip install -r requirements.txt
# download t1maps
python make_pooled_datasets.py configs/3T_NIST_t1maps.json 3T_NIST_t1maps
# download mag/phase data
python make_pooled_datasets.py configs/3T_NIST.json 3T_NIST
# register
python register_t1maps_nist.py -j configs/3T_NIST.json -p 3T_NIST_pooled/ 3T_NIST_T1maps_pooled/
~~~

Not addressed in this PR: application of inverse transform to the mask sphere. This is easy to do (single line of code), but would require the existence of such a mask.

### CODE REVIEW

**Comment by jcohenadad** [comment]
@mathieuboudreau trying to make a general script that takes as input the mag data. At first, i wanted to assume that all magnitude multi-component data have the suffix `NIST.nii.gz`, before realizing an exception (maybe more): `20200210_guillaumegilbert_muhc_NIST_Magnitude.nii.gz`.

Do you have any tips for me, about how we can generalize the script without making ugly "if cases"?

**Comment by mathieuboudreau** [comment]
@jcohenadad I could probably code up something, but I think since there are only about 50 datasets and most of them are already standardized, the simplest and cleanest solution would be for me to just rename and reupload the outliers. I'll try to do it in the next two days.

**Comment by jcohenadad** [comment]
> @jcohenadad I could probably code up something, but I think since there are only about 50 NIST datasets and most of them are already standardized, the simplest and cleanest solution would be for me to just rename and reupload the outliers. I'll try to do it in the next two days.

to avoid you wasting time unnecessarily (i.e. in case the magnitude-based registration does not provide improvements),  i can start coding something that would work for all the _NIST data, and if we find a sensible improvement over the t1map-based registration, then you could go ahead and rename the remaining files. Does that sound good?

**Comment by jcohenadad** [comment]
@mathieuboudreau i'm currently refactoring the .sh file into python (for more convenient usage/debugging). I'd love to use your configs/json files as input for the registration script, but i am confused by the organization of the json file. For example, between
this site:
https://github.com/rrsg2020/analysis/blob/8be5e8dd37a733cc8171d3d8a2f3f28ff8fca702/configs/3T_NIST.json#L5

and this site:
https://github.com/rrsg2020/analysis/blob/8be5e8dd37a733cc8171d3d8a2f3f28ff8fca702/configs/3T_NIST.json#L23

the key changes ("magnitude" vs. "one"). I'm sure there is a particular reason for it, but i am wondering what would be the best solution to fetch a particular data per site, in a systematic way (i.e. loop across first-level json keys, with the same second- or third-level key). 

alternatively, i am thinking into creating another json file, that would only be used for processing, and that would point to the appropriate dataset. Or, a more elegant would be to modify the current json file and add processing-specific keys.  Unless you have a better idea.

**Comment by mathieuboudreau** [comment]
@jcohenadad I had to give datasets "names", because while one site only submitted one datasets (i.e. data to create 1 T1 map), other sites submitted several. For example, some only 1 acquired dataset but enough files to fit T1 map using magnitude-only and another one using complex data, or other ones different session & scanners, like: 

https://github.com/rrsg2020/analysis/blob/8be5e8dd37a733cc8171d3d8a2f3f28ff8fca702/configs/3T_NIST.json#L40

I just named `one` the ones that only gave one dataset, because I couldn't think of a better name at the moment. 

I'd recommend you look at my code to see how I parse between sites and then within datasets in this Jupyter Notebook (in 
Get configuration options) : https://github.com/rrsg2020/t1_fitting_pipeline/blob/master/RRSG_T1_fitting.ipynb. Basically you should loop between sites (e.g. top-level keys of the json file, i.e. `"matthewgrechsollars_ICL_NIST"`), and then for each site loop between the datasets (i.e. the `datasets` key after you've selected a site). For each dataset structure that you've selected, you can look at the value of the `dataType` key to see what kind type of data is configured for this dataset (e.g. `Magnitude` means that you can get "imagePath" directly, whereas if `dataType` is `Complex`, then you have to get both the real and imaginary or magnitude and phase paths, which are their own substructures)

I think I did to confuse you is that I used the names "magnitude" or "complex" for both the name of the key for the **dataset** in some cases, but also also as the value for the `dataType` keys for every dataset. If you'd like, we could have a quick videocall so that I can clear some of this up to you.

**Comment by mathieuboudreau** [comment]
> (i.e. loop across first-level json keys, with the same second- or third-level key).

I don't think this is possible, because the dataset names need to be more descriptive than simply "magnitude" or "complex" for many sites. For example, look at all the datasets that "CStehningPhilipsClinicalScienceGermany_NIST" submitted. They are all from different sites or scanners, so I gave them all unique dataset names.

**Comment by jcohenadad** [comment]
Thank you for the explanation @mathieuboudreau, all good. I've started a working prototype, it will be straightforward to port the bash script (`register_t1maps_nist.sh`) into a similar python script than the one you already made (`make_pooled_datasets.py`). Usage for will therefore be intuitive (because similar between our two scripts).

<details><summary>Example of usage (with a050bb4f331d4200c27b7beb48eedbd21eedf2bb)</summary>

~~~
julien-macbook:~/code/rrsg2020_analysis $ python register_t1maps_nist.py configs/3T_NIST.json 3T_NIST

Processing: 3T_NIST/20200121_matthewgrechsollars_ICL_NIST_Magnitude.nii.gz

Processing: 3T_NIST/20200124_siyuanhu_casewestern_NIST.nii.gz

Processing: 3T_NIST/20200203_iveslevesque_muhc_mgh_NIST.nii.gz

Processing: 3T_NIST/20200204_mrel_usc_GE3T_MR1_NIST.nii.gz

Processing: 3T_NIST/20200204_mrel_usc_GE3T_MR2_NIST.nii.gz

Processing: 3T_NIST/20200209_mrel_usc_GE3T_MR1_NIST.nii.gz

Processing: 3T_NIST/20200209_mrel_usc_GE3T_MR1_NIST_TR10sec.nii.gz

Processing: 3T_NIST/20200209_mrel_usc_GE3T_MR2_NIST.nii.gz

Processing: 3T_NIST/20200209_mrel_usc_GE3T_MR2_NIST_TR10sec.nii.gz

Processing: 3T_NIST/20200210_guillaumegilbert_muhc_NIST_Magnitude.nii.gz

Processing: 3T_NIST/Aachen_MR1_magnitude.nii.gz

Processing: 3T_NIST/Berlin_MR1_magnitude.nii.gz

Processing: 3T_NIST/Bonn_MR1_magnitude.nii.gz

Processing: 3T_NIST/Cologne_MR1_magnitude.nii.gz

Processing: 3T_NIST/Cologne_MR3_magnitude.nii.gz

Processing: 3T_NIST/Cologne_MR4_magnitude.nii.gz

Processing: 3T_NIST/Hamburg_MR1_magnitude.nii.gz

Processing: 3T_NIST/20200226_iveslevesque_muhc_glen_NIST_PowerError.nii.gz

Processing: 3T_NIST/20200226_iveslevesque_muhc_glen_NIST_NoPowerError.nii.gz

Processing: 3T_NIST/20191213_karakuzu_UNF_NIST_FS.nii.gz

Processing: 3T_NIST/20200227_karakuzu_mni_NIST_FS.nii.gz

Processing: 3T_NIST/20200227_madelinecarr_lha_NIST.nii.gz

Processing: 3T_NIST/20200229_niloufar_hfmc_NIST_4point.nii.gz

Processing: 3T_NIST/20200229_niloufar_hfmc_NIST_14point.nii.gz

Processing: 3T_NIST/day1_magn.nii.gz

Processing: 3T_NIST/day2_magn.nii.gz

Processing: 3T_NIST/20200305_ngmaforo_ucla_NIST_Prisma_noFS.nii.gz

Processing: 3T_NIST/20200305_ngmaforo_ucla_NIST_Prisma_FS.nii.gz

Processing: 3T_NIST/20200305_ngmaforo_ucla_NIST_Skyra_noFS.nii.gz

Processing: 3T_NIST/20200305_ngmaforo_ucla_NIST_Skyra_FS.nii.gz

Processing: 3T_NIST/20200309_near_douglas_NIST.nii.gz
~~~

</details>

**Comment by mathieuboudreau** [comment]
@jcohenadad following up on a previous point:

> @jcohenadad I could probably code up something, but I think since there are only about 50 NIST datasets and most of them are already standardized, the simplest and cleanest solution would be for me to just rename and reupload the outliers. I'll try to do it in the next two days.

I've decided to standardize the filenames, and have just completed doing so for the 3T NIST datasets. I've uploaded the renamed files to OSF. I've also uploaded the updated configuration scripts and your registration script to this repository. **Your scripts might be currently broken.** You should first merge master to your branch(es). 

Here are the changes that I've made, so that you know how to update your scripts:
* All raw dataset files now end with `_NIST_Magnitude.nii.gz`, `_NIST_Phase.nii.gz`, `_NIST_Real.nii.gz`, or `_NIST_Imaginary.nii.gz`
* All T1 map files now end with `_T1map.nii.gz`
* Some of the files prefixes have also been renamed to be more consistent with the ordering of where `NIST` is located (e.g. [your script's reference file](https://github.com/rrsg2020/analysis/commit/c6b0a96f8aa1c0c3b0d8739397650b42c6bf7c4e))

Hope this doesn't cause you too much of a headache, but I think moving forward this will be for the best.

**Comment by jcohenadad** [comment]
> Hope this doesn't cause you too much of a headache, but I think moving forward this will be for the best.

no worries, thank you @mathieuboudreau it will be cleaner moving forward indeed

**Comment by jcohenadad** [comment]
@mathieuboudreau did you remove the manual labels from the 3T_NIST data? i remember seeing them in the previous version of the bundled OSF data.

**Comment by mathieuboudreau** [comment]
@jcohenadad No I only ever added the labels to the 3T_NIST_T1map datasets on OSF, since your last script only worked with those datasets. They should be the same labels as needed for the raw data in 3T_NIST I think, just wtihout the `_T1map` suffix to the filenames.

**Comment by jcohenadad** [comment]
> They should be the same labels as needed for the raw data in 3T_NIST I think, just wtihout the _T1map suffix to the filenames.

to avoid duplication i will just grab those labels from the `3T_NIST_T1map/` folder

**Comment by jcohenadad** [comment]
working prototype 1b1a6e8: 
~~~
python register_t1maps_nist.py -j configs/3T_NIST.json -p 3T_NIST_pooled/ 3T_NIST_T1maps_pooled/
~~~
Results:
mag_reg

Next steps:
- Investigate use of other echoes
- Investigate slightly different registration mask
- Replace gifmaker system call by API
- Apply inverse transformations to sphere mask (will be used to quantify T1 in native space)

**Comment by jcohenadad** [comment]
comparing e0 and e2 for registration:
mag_e0_reg
mag_e2_reg

we might want to apply transformations on the same contrast (for easier visual comparison)

**Comment by jcohenadad** [comment]
getting there!
mag_e2_reg-bsplinesyn-syn0 5

**Comment by mathieuboudreau** [comment]
Awesome!

p.s. We could probably remove the two datasets that were acquired on the wrong plates (you can tell by the position of the three reference tubes) from the json so that they are removed from the pipelines - they should be discarded or compared separately.

**Comment by jcohenadad** [comment]
> p.s. We could probably remove the two datasets that were acquired on the wrong plates (you can tell by the position of the three reference tubes) from the json so that they are removed from the pipelines - they should be discarded or compared separately.

i'll remove them from the json

**Comment by jcohenadad** [comment]
1a781a9d050b4464305701b025f248de377306fd added site for convenience: 
results_reg_20200702213920

**Comment by jcohenadad** [comment]
de5faa012ae0b88067deedd34f4e388d6ad04b83 Excluded:
- `20200305_ngmaforo_ucla_Prisma_noFS_NIST_Magnitude.nii.gz`
- `20200305_ngmaforo_ucla_Prisma_FS_NIST_Magnitude.nii.gz`

Remaining issue:
- `20200229_niloufar_hfmc_NIST/20200229_niloufar_hfmc_14point_NIST_Magnitude.nii.gz` → no signal nulling at 3rd echo. We could make an exception for this site and find the appropriate echo for registration.

**Comment by mathieuboudreau** [comment]
@jcohenadad I'm now reviewing this branch.

I tried your installation/running instructions, however I encountered an error when calling the final script.

```shell

(rrsg_analysis) mathieuboudreau@mathieu analysis % python register_t1maps_nist.py -j configs/3T_NIST.json -p 3T_NIST_pooled/ 3T_NIST_T1maps_pooled/
fslsplit 3T_NIST_pooled/20200210_guillaumegilbert_muhc_NIST_Magnitude.nii.gz 3T_NIST_pooled/20200210_guillaumegilbert_muhc_NIST_Magnitude_echo.nii.gz -t
Traceback (most recent call last):
  File "register_t1maps_nist.py", line 169, in <module>
    main()
  File "register_t1maps_nist.py", line 103, in main
    fname_mag_ref = extract_volume(fname_mag_ref, NUM_ECHO)
  File "register_t1maps_nist.py", line 76, in extract_volume
    run_subprocess('fslsplit {} {} -t'.format(fname_nii, add_suffix(str(fname_nii), '_echo')))
  File "register_t1maps_nist.py", line 65, in run_subprocess
    subprocess.run(cmd.split(' '), stdout=subprocess.PIPE, text=True)
  File "/Users/mathieuboudreau/anaconda3/envs/rrsg_analysis/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'text'
(rrsg_analysis)

```

Any clue why?

Here's the pip freeze output for my conda venv:

```shell

(rrsg_analysis) mathieuboudreau@mathieu analysis % pip freeze
certifi==2020.6.20
chardet==3.0.4
gifmaker==1.3
idna==2.9
imageio==2.8.0
numpy==1.19.0
Pillow==7.1.2
requests==2.24.0
scipy==1.5.0
tqdm==4.46.1
urllib3==1.25.9
wget==3.2

```

Here's the version of Python I'm running:

```shell
(rrsg_analysis) mathieuboudreau@mathieu analysis % python
Python 3.6.10 |Anaconda, Inc.| (default, May  7 2020, 23:06:31) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

**Comment by jcohenadad** [comment]
@mathieuboudreau likely related to [this](https://stackoverflow.com/questions/52663518/python-subprocess-popen-doesnt-take-text-argument). We could either remove the extra argument, or require py37. Any preference?

**Comment by mathieuboudreau** [comment]
> @mathieuboudreau likely related to [this](https://stackoverflow.com/questions/52663518/python-subprocess-popen-doesnt-take-text-argument). We could either remove the extra argument, or require py37. Any preference?

Ahh kk. I'm happy to require Python 3.7, as I want to encourage people to run this in a conda virtual environment anyways.

Thanks ! The script running now

**Pull request merged**
